### ISSUE TITLE
[Request] Setup instructions

### ISSUE THREAD

**Issue by crykn** [jehob/rlc_app#38]
I'm currently trying to setup your application locally to get a look at how it works, but I'm struggling a bit. I installed VS Code, Python, etc. and got the project running in/with django. The problem is I can only access _/admin_ and _/api_; all other sites are are just a blank page (the one in _static/index.html_). Am I simply not finding the right URL to access the application or did I mess up the django installation/settings? 
My experience with python and django in particular are very limited, so it's not really obvious to me how to go about setting this all up. It would be useful if there were some simple instructions on how to setup the application in your wiki.

**Comment by jehob** [comment]
I updated the readme.md and added installation instructions for local development. 

The problem was in short, that you have to compile the angular part which is then served by Django.
I hope that will help you, if not, please open another issue.
