### ISSUE TITLE
How to setup an admin user?

### ISSUE THREAD

**Issue by crykn** [jehob/rlc_app#39]
Thanks to your instructions I was able to set up my local environment, but I'm still having one issue:
I am lacking a user, that has sufficient permissions to do anything. The one created by `python manage.py createsuperuser` doesn't seem to have any permissions (indicated by the lack of items in the sidebar). So far, my tries in creating a user with the django shell were unsuccessful as well. Is there any (simple) way to create a user that has all permissions?

**Comment by jehob** [comment]
Unfortunately the superusere is at the moment just able to view and alter the backend data through the browsable api of django ({url}/api/ or {url}/api/records/). To use the system as intended either use the command "create_dummy_data" with "python manage.py create_dummy_data", which will give you a fully featured dummy rlc with one full example record ("AZ-001/18"), or use the create_new_rlc with the correct params to create an empty rlc and admin account for that rlc, to see which commands are mandatory see file: create_new_rlc.py in api/management/commands.
For testing purposes I would recommend the dummy-data command. After creation you can login with the credentials: "dummy@rlcm.de"/"qwe123", for details see file: create_dummy_data.py in api/management/commands.

**Comment by crykn** [comment]
Thanks!
